version: '3.7'
services:
  nginx:
    container_name: lz-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  redis:
    container_name: lz-redis
    image: redis:latest
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - /var/www/hackathon/redis:/data/
    restart: unless-stopped

  mysql:
    container_name: lz-mysql
    image: mysql/mysql-server:8.0.18
    environment:
      MYSQL_DATABASE: db_test
      MYSQL_USER: guest
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      -  /conf/mysql:/etc/mysql/conf.d
      -  /var/www/hackathon/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped

  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./log/:/app/log/
      - .:/app
    expose:
      - 8080:8080
    depends_on:
      - mysql
      - redis