version: '3.7'
services:
  nginx:
    container_name: lz-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/nginx/conf.d:/etc/nginx/conf.d
      - /root/cert:/root/cert
    depends_on:
      - app
    networks:
      - backend

  redis:
    container_name: lz-redis
    image: redis:latest
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
      - /var/www/hackathon/redis:/data/
    restart: unless-stopped
    networks:
      - backend

  mysql:
    container_name: lz-mysql
    image: mysql/mysql-server:8.0.18
    environment:
      MYSQL_DATABASE: db_test
      MYSQL_USER: guest
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      -  /conf/mysql:/etc/mysql/conf.d
      -  /var/www/hackathon/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - backend

  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    volumes:
      - $PWD/log/:/log
      - $PWD:/app
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis
    networks:
      - backend

networks:
  backend: